### ISSUE TITLE
Argo Tunnel (Warp) does not work anymore

### ISSUE THREAD

**Issue by rimusz** [cloudflare/cloudflare-ingress-controller#21] opened 2018-04-04 13:06 UTC
Moving Warp to Argo Tunnel this ingress does not work anymore.
Enabled Argo tunnel and LoadBalancer for my domain, but still getting error:
```
level=error msg="Server error: error creating new pool demo.mydomain.com: authentication error: response: {\n  \"result\": null,\n  \"success\": false,\n  \"errors\": [\n    {\n      \"code\": 1002,\n      \"message\": \"the origin list length must be in range [1, 0]: validation failed\"\n    }\n  ],\n  \"messages\": []\n}\n"
```

**Comment by rimusz** [comment] 2018-04-04 13:06
cc @ntfrnzn

**Comment by vpetersson** [comment] 2018-04-25 18:29
+1

**Comment by tbh1** [comment] 2018-05-05 01:51
It looks like this will only work for enterprise accounts until the lb test is either optional or at least configurable. The docs don't mention purchasing a load balancer or an enterprise account. The last commit I've been able to get working is 6407f03 but that has other issues.

A quick look, issue seems to start [here](https://github.com/cloudflare/cloudflare-ingress-controller/blob/master/pkg/controller/controller.go#L546)
Relevant? config [here]( https://github.com/cloudflare/cloudflare-go/blob/master/load_balancing.go#L25)

**Comment by daviesalex** [comment] 2018-05-08 20:01
I put a ticket in with Cloudflare, who confirmed that this is expected - you need a LB for this to work:

> Our team have confirmed that you need to have Cloudflare Load-Balancing enabled in order to use tunnel as your ingress-controller. So, plan type doesn't cause the error in this case. They are looking at the possibility to allow users that don't have load-balancing enabled to specify a config option so that they can still set up the ingress controller, but we don't have an ETA on that as yet.

We are using a sidecart container to run cloudflared for now, which is working fine for our fairly low load problems.

**Comment by ntfrnzn** [comment] 2018-05-21 17:49
https://github.com/cloudflare/cloudflare-ingress-controller/pull/26 will default load-balancing to off

**Comment by tonyxiao** [comment] 2018-08-12 18:14
@ntfrnzn  does that mean the issue has been fixed and can now be closed?

**Comment by mattalberts** [comment] 2018-10-01 19:52
I'm closing this issue. The default deployment and helm chart do not require a load-balancer.  However, if the ingress-controller deployment has replicas >= 1, a load-balancer is required.  The documents have been updated to reflect the requirement (it might need to be spelled out more prominently)

**Closed by mattalberts** 2018-10-01 19:52 UTC

**Comment by tonyxiao** [comment] 2018-10-03 16:44
the replicas >= 1 then load balancer is required part totally escaped me. Yes @mattalberts i think it should be more explicit
