### ISSUE TITLE
Probing from every data centre is not allowed with this subscription

### ISSUE THREAD

**Issue by alahijani** [cloudflare/cloudflare-ingress-controller#18] opened 2018-03-26 05:02 UTC
I get an error similar to this when I try the basic instructions, even though `cloudflared --hello-world` works for this account and domain name. 

Is there a way to get more information out if it to see what I'm doing wrong?

```
ERRO[0037] Server error: error creating new pool <domain name>: authentication error: response: {
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 1002,
      "message": "Probing from every data centre is not allowed with this subscription. Please choose regions to probe from.: validation failed"
    }
  ],
  "messages": []
}
```

**Comment by kcl11** [comment] 2018-04-27 08:53
+1

**Comment by riaan53** [comment] 2018-05-09 11:25
Im also getting this error. Anyone able to solve it?

**Comment by alex-mayorga** [comment] 2018-05-11 20:39
¡Hola!

To get it to work you can edit the load balancer to remove all regions from the health check.

¡Gracias!

**Comment by barrymac** [comment] 2018-06-07 13:52
In the latest version of the helm chart with image 0.5.1 you can set the loadbalancer option to false and it will work without having a load balancer

**Comment by mattalberts** [comment] 2018-10-01 19:41
I'm spring cleaning issues.  the issue appears to have been resolved by removing the load-balancer requirement. I'm closing the issue (we can reopen or create a new issue tracking against 0.5.3 if the problem is not resolved).

**Closed by mattalberts** 2018-10-01 19:41 UTC
